version: "3.9"

services:
  supabase-db:
    image: supabase/postgres:15.6.1.83
    container_name: supabase-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - supabase-db:/var/lib/postgresql/data
      - ../db/init.sql:/docker-entrypoint-initdb.d/01-init.sql:ro

  kong:
    image: kong:3.6
    container_name: supabase-kong
    restart: unless-stopped
    environment:
      KONG_DATABASE: off
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
    ports:
      - "8000:8000"
      - "8443:8443"
    volumes:
      - supabase-kong:/var/lib/kong

  supabase-rest:
    image: postgrest/postgrest:v12.2.3
    container_name: supabase-rest
    restart: unless-stopped
    depends_on:
      - supabase-db
    environment:
      PGRST_DB_URI: postgres://postgres:${POSTGRES_PASSWORD}@supabase-db:5432/postgres
      PGRST_DB_SCHEMAS: public
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET}
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:54321
    ports:
      - "54321:3000"

  gotrue:
    image: supabase/gotrue:v2.164.2
    container_name: supabase-auth
    restart: unless-stopped
    depends_on:
      - supabase-db
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      GOTRUE_DB_DRIVER: postgres
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@supabase-db:5432/postgres?sslmode=disable
      GOTRUE_SITE_URL: http://localhost:5173
      GOTRUE_JWT_SECRET: ${JWT_SECRET}
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_DISABLE_SIGNUP: "false"
      GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
      GOTRUE_MAILER_AUTOCONFIRM: "true"
      GOTRUE_LOG_LEVEL: info
    ports:
      - "9999:9999"

  storage:
    image: supabase/storage-api:v1.0.7
    container_name: supabase-storage
    restart: unless-stopped
    depends_on:
      - supabase-db
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://supabase-rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@supabase-db:5432/postgres?sslmode=disable
      FILE_SIZE_LIMIT: 5242880
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
    volumes:
      - supabase-storage:/var/lib/storage
    ports:
      - "5000:5000"

  realtime:
    image: supabase/realtime:v2.25.64
    container_name: supabase-realtime
    restart: unless-stopped
    depends_on:
      - supabase-db
    environment:
      DB_HOST: supabase-db
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4000:4000"

volumes:
  supabase-db:
  supabase-kong:
  supabase-storage:
